# Generated by Django 5.2.17 on 2026-09-29 17:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('active', 'ativa'), ('archived', 'arquivada')], default='active', max_length=20, verbose_name='status')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='apagada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(verbose_name='sequência')),
                ('role', models.CharField(choices=[('system', 'sistema'), ('user', 'usuário'), ('assistant', 'assistente'), ('tool', 'ferramenta')], max_length=20, verbose_name='papel')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens do prompt')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens da resposta')),
                ('finish_reason', models.CharField(blank=True, max_length=50, verbose_name='motivo de término')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fact', 'fato'), ('preference', 'preferência'), ('summary', 'resumo')], max_length=20, verbose_name='tipo')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('importance', models.SmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='importância')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usada por último em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='chat.message', verbose_name='mensagem de origem')),
            ],
            options={
                'verbose_name': 'memória',
                'verbose_name_plural': 'memórias',
                'ordering': ['-importance', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='chat_conv_user_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='chat_message_unique_conversation_seq'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'is_active', '-importance'], name='chat_mem_user_active_imp_idx'),
        ),
    ]
