# Generated by Django 5.2.17 on 2026-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_conversation_message_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_conversation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID da conversa no RealocAI'),
        ),
    ]
