# Generated by Django 5.2.17 on 2026-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_external_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='memory_extracted_seq',
            field=models.PositiveIntegerField(default=0, verbose_name='última sequência processada para memória'),
        ),
    ]
