# Generated by Django 5.2.17 on 2026-10-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_memory_extracted_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='preview',
            field=models.CharField(blank=True, default='', max_length=90, verbose_name='prévia'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processamento iniciado em'),
        ),
        migrations.AddField(
            model_name='message',
            name='blocos',
            field=models.JSONField(blank=True, default=list, verbose_name='blocos de relatório'),
        ),
    ]
